/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spdvi.toolsmanager2tex.panels;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import spdvi.toolsmanager2tex.Main;
import spdvi.toolsmanager2tex.data.DataAccess;
import spdvi.toolsmanager2tex.models.Eina;
import spdvi.toolsmanager2tex.models.Usuari;

/**
 *
 * @author Miguel
 */
public class InventariPanel extends javax.swing.JPanel {
    private JList<Usuari> lstUsuaris;
    DataAccess da = new DataAccess();

    /**
     * Creates new form InventariPanel
     */
    public InventariPanel() {
        initComponents();
        lstUsuaris = new JList<Usuari>();
        jScrollPane2.setViewportView(lstUsuaris);
        
        lstUsuaris.addListSelectionListener((javax.swing.event.ListSelectionEvent evt) ->
        {
            lstUsuarisValueChanged(evt);
        });
    }
    
    private  void lstUsuarisValueChanged(ListSelectionEvent evt){
        pnlEines.removeAll();
        repaint();
        Usuari selectedUser= lstUsuaris.getSelectedValue();
        ArrayList<Eina> eines = da.getTools(selectedUser.getId());
        for(Eina e: eines){
            ImatgePanel imatgePanel = new ImatgePanel();
            imatgePanel.setNomEina(e.getNom());
            imatgePanel.setImagePath(e.getFoto());
            pnlEines.add(imatgePanel);
        }
        ((JFrame)(this.getRootPane().getParent())).pack();
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEines = new javax.swing.JPanel();
        btnEines = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnUsuaris = new javax.swing.JButton();

        btnEines.setText("Get eines");
        btnEines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEinesActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        btnUsuaris.setText("Get Usuaris");
        btnUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEines, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUsuaris)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEines, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jTextField1)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuaris)
                        .addGap(18, 18, 18)
                        .addComponent(btnEines)
                        .addGap(50, 50, 50)))
                .addComponent(pnlEines, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEinesActionPerformed
        ArrayList<Eina> eines = da.getTools(Integer.parseInt(jTextField1.getText()));
//        
//        for (Eina e : eines) {
//            ImatgePanel imatgePanel = new ImatgePanel();
//            imatgePanel.setNomEina(e.getNom());
//            imatgePanel.setImagePath(e.getFoto());
//            pnlEines.add(imatgePanel);
//        }
        for(Eina e: eines){
            ImatgePanel imatgePanel = new ImatgePanel();
            imatgePanel.setNomEina(e.getNom());
            imatgePanel.setImagePath(e.getFoto());
            pnlEines.add(imatgePanel);
        }
        
        
        /*ArrayList<JButton> botones = new ArrayList<>();

        botones.add(new JButton("Boton 1"));
        botones.add(new JButton("Boton 2"));
        botones.add(new JButton("Boton 3"));
        
        for(JButton b: botones) {
            pnlEines.add(b);
        }*/
        ((JFrame)(this.getRootPane().getParent())).pack();
    }//GEN-LAST:event_btnEinesActionPerformed

    private void btnUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarisActionPerformed
        DataAccess da = new DataAccess();

        try {
            var usuaris = da.getUsuaris();
            DefaultListModel<Usuari> dfmu = new DefaultListModel<>();
            for(Usuari u: usuaris) {
                dfmu.addElement(u);
            }
            lstUsuaris.setModel(dfmu);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUsuarisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEines;
    private javax.swing.JButton btnUsuaris;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlEines;
    // End of variables declaration//GEN-END:variables
}
