/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spdvi.toolsmanager2tex.panels;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import spdvi.toolsmanager2tex.Main;
import spdvi.toolsmanager2tex.data.DataAccess;
import spdvi.toolsmanager2tex.models.Usuari;
import spdvi.toolsmanager2tex.utils.ImageUtils;

/**
 *
 * @author Miguel
 */
public class ListUsersPanel extends javax.swing.JPanel {
    private JList<Usuari> lstUsuaris;
    /**
     * Creates new form ListUsersPanel
     */
    public ListUsersPanel() {
        initComponents();
        lstUsuaris = new JList<Usuari>();
        jScrollPane2.setViewportView(lstUsuaris);
        
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuarisValueChanged(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListUsers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImageUsuari = new javax.swing.JLabel();

        btnListUsers.setText("List users");
        btnListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUsersActionPerformed(evt);
            }
        });

        lblImageUsuari.setText("lblImageUsuari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListUsers)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(lblImageUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnListUsers)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblImageUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstUsuarisValueChanged(javax.swing.event.ListSelectionEvent evt) {                                    
        try
        {
            // TODO add your handling code here:
            Usuari selectedUser = lstUsuaris.getSelectedValue();
            System.out.println("user "+selectedUser);
            System.out.println("foto "+selectedUser.getFoto().trim());
            // Cargar imatge del usuari
            
            URL  url = new URL(selectedUser.getFoto());
            System.out.println("URL: "+ url);
            //ERROR 
            BufferedImage bi = ImageIO.read(new URL(selectedUser.getFoto()));
            //Error
            System.out.println("Image "+bi);
            ImageIcon icon = ImageUtils.resizeImageIcon2(bi, 200, 200);
            lblImageUsuari.setIcon(icon);
            lblImageUsuari.setText("");
        } catch (IOException ex)
        {
            Logger.getLogger(ListUsersPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }  
    
    private void btnListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUsersActionPerformed
        DataAccess da = new DataAccess();

        try {
            var usuaris = da.getUsuaris();
            DefaultListModel<Usuari> dfmu = new DefaultListModel<>();
            for(Usuari u: usuaris) {
                dfmu.addElement(u);
            }
            lstUsuaris.setModel(dfmu);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListUsers;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImageUsuari;
    // End of variables declaration//GEN-END:variables
}
