package spdvi.toolsmanager2tex.panels;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import spdvi.toolsmanager2tex.data.DataAccess;
import spdvi.toolsmanager2tex.models.Usuari;
import spdvi.toolsmanager2tex.utils.Constants;

/**
 *
 * @author Lluis    
 */
public class LoginPanel extends javax.swing.JPanel {
    static String Users = Constants.UsersPath;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblName.setText("UserName");

        lblPassword.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnLogin))
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addGap(7, 7, 7)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String pssw = txtPassword.getText();
        String username = txtUsername.getText();
        boolean exists = checkUserExists(username, pssw);     
            if(exists){
                //setLoggedUser();
            }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /*
    public void setData(String username,String name,String surname, String email,String img){
        
        lblUsername.setText(username);
        lblName.setText(name+surname);
        lblEmail.setText(email);
        
        URL  url = new URL(img);
        BufferedImage rawimg = ImageIO.read(url);
        ImageIcon img = da.resizeImageIcon2(rawimg, lblUserImg.getWidth(), lblUserImg.getHeight());
        lblUserImg.setIcon(img);
    }
    */
    static boolean UserExists = false;
    private static boolean checkUserExists(String name,String passw){
        DataAccess da = new DataAccess();
        
        try
        {
            ArrayList<Usuari> users = new ArrayList<>();
            users = da.getUsuaris();
            String namec;
            String emailc;
            for(Usuari user : users){
                System.out.println("u: "+user);
                namec = user.getUsername().trim();
                System.out.println(user.getUsername().trim());
                System.out.println("namec: "+ namec);
                emailc = user.getPassword();
                if(namec.contains(name) || emailc.contains(passw)){
                    UserExists = true;
                    return UserExists;
                }
            }
            System.out.println("UserExists: "+ UserExists);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(UserExists);
        return UserExists;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
