package spdvi.toolsmanager2tex;

import java.awt.Component;
import spdvi.toolsmanager2tex.panels.InventariPanel;
import spdvi.toolsmanager2tex.panels.ListUsersPanel;
import spdvi.toolsmanager2tex.panels.LoginPanel;
import spdvi.toolsmanager2tex.panels.RegisterPanel;

/**
 *
 * @author Lluis
 */
public class Main extends javax.swing.JFrame {

//    LoginPanel pnlLogin = null;
//    ListUsersPanel usersPanel = null;
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniRegister = new javax.swing.JMenuItem();
        mniProfile = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mnuActions = new javax.swing.JMenu();
        mniSessions = new javax.swing.JMenuItem();
        mniListUsers = new javax.swing.JMenuItem();
        mniInventari = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));

        mnuUser.setText("Login");
        mnuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserActionPerformed(evt);
            }
        });

        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuUser.add(mniLogin);

        mniRegister.setText("Register");
        mniRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegisterActionPerformed(evt);
            }
        });
        mnuUser.add(mniRegister);

        mniProfile.setText("My profile");
        mnuUser.add(mniProfile);

        mniLogout.setText("Logout");
        mnuUser.add(mniLogout);

        jMenuBar1.add(mnuUser);

        mnuActions.setText("Actions");

        mniSessions.setText("Sessions");
        mnuActions.add(mniSessions);

        mniListUsers.setText("List Users");
        mniListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListUsersActionPerformed(evt);
            }
        });
        mnuActions.add(mniListUsers);

        mniInventari.setText("Inventari");
        mniInventari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInventariActionPerformed(evt);
            }
        });
        mnuActions.add(mniInventari);

        jMenuBar1.add(mnuActions);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserActionPerformed

    }//GEN-LAST:event_mnuUserActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        hideActivePanel();
//        if (pnlLogin == null) {
//            pnlLogin = new LoginPanel();
//            getContentPane().add(pnlLogin, java.awt.BorderLayout.CENTER);
//            pack();
//        } else {
//            pnlLogin.setVisible(true);
//        }
        LoginPanel pnlLogin = new LoginPanel();
        getContentPane().add(pnlLogin, java.awt.BorderLayout.CENTER);
        pack();
//        } else {
//            pnlLogin.setVisible(true);
//        }

    }//GEN-LAST:event_mniLoginActionPerformed

    /*
    public void setLoggedUserData(){
        LoggedUPanel pnlLoggedUser = new LoggedUPanel();
        getContentPane().add(pnlLoggedUser, java.awt.BorderLayout.CENTER);
        pack();
    }
    */
    
    private void mniListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListUsersActionPerformed
        hideActivePanel();
//        if (usersPanel == null) {
//            usersPanel = new ListUsersPanel();
//            getContentPane().add(usersPanel, java.awt.BorderLayout.CENTER);
//            pack();
//        } else {
//            usersPanel.setVisible(true);
//        }

        ListUsersPanel usersPanel = new ListUsersPanel();
        getContentPane().add(usersPanel, java.awt.BorderLayout.CENTER);
        pack();

    }//GEN-LAST:event_mniListUsersActionPerformed

    private void mniInventariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInventariActionPerformed
        hideActivePanel();
        InventariPanel inventariPanel = new InventariPanel();
        getContentPane().add(inventariPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mniInventariActionPerformed

    private void mniRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegisterActionPerformed
        hideActivePanel();
        RegisterPanel registerPanel = new RegisterPanel();
        getContentPane().add(registerPanel, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mniRegisterActionPerformed

    private void hideActivePanel() {
        Component[] panels = getContentPane().getComponents();
        for (Component c : panels) {
            if (c.isVisible()) {
//                c.setVisible(false);
                getContentPane().remove(c);
                c = null;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniInventari;
    private javax.swing.JMenuItem mniListUsers;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniProfile;
    private javax.swing.JMenuItem mniRegister;
    private javax.swing.JMenuItem mniSessions;
    private javax.swing.JMenu mnuActions;
    private javax.swing.JMenu mnuUser;
    // End of variables declaration//GEN-END:variables
}
